Add which and diff, Cryptopolicies, Speed up image building by reducing layers
dmwm/cms_consistency pull request #5
Opened 2024-06-12 20:32 UTC by d-ylee

Added which and diff to image. Set a default crypto policy.

Speed up the image by combining and reducing layers

2024-06-13 21:47 UTC, ericvaandering requested changes

2024-06-13 21:47 UTC, ericvaandering commented on docker/Dockerfile
> +    dnf install -y osg-pki-tools && \
While it's nice to have the repo on it's own dnf line, I think you can go further by collapsing the rest of the package installs into one command.

2025-02-21 19:59 UTC, mrguilima reviewed
The "diff" command is already available in current consistency image, while the "which" command  is not.
The update-crypto-policies was also not part of current running image.

2025-03-05 17:22 UTC, ericvaandering commented
If this is still needed, please fix the conflicts.

2025-03-31 21:35 UTC, mrguilima approved these changes
These changes look good to me.
The changes are required to improve the resilience of the consistency jobs against restarts of the consistency pod.

2025-04-02 20:29 UTC, ericvaandering commented
This looks good to me. Shall I merge?

2025-04-03 12:12 UTC, mrguilima commented
I think so, yes.

2025-04-03 14:47 UTC, merged